const spellList = [
    {
      "effect": "Choose any number of creatures you can see: each of them suffers **(choose one: dazed, shaken, slow, weak)**.",
      "special": [],
      "type": "",
      "mp": "20",
      "damagetype": "physical",
      "target": "Special",
      "itemType": "spell",
      "attr2": "will",
      "duration": "Instantaneous",
      "attr1": "insight",
      "name": "Area Status",
      "maxTargets": 0
    },
    {
      "mp": "5",
      "target": "One creature",
      "attr1": "insight",
      "name": "Breath",
      "type": "offensive",
      "effect": "The target suffers **【HR + 10】 (choose type)** damage.",
      "special": [],
      "damagetype": "physical",
      "itemType": "spell",
      "attr2": "will",
      "duration": "Instantaneous",
      "maxTargets": 1
    },
    {
      "itemType": "spell",
      "attr2": "will",
      "duration": "Instantaneous",
      "attr1": "insight",
      "special": [],
      "maxTargets": 1,
      "mp": "5",
      "effect": "The target suffers **(choose one: dazed, shaken, slow, weak)**.",
      "name": "Curse",
      "target": "One creature",
      "damagetype": "physical",
      "type": "offensive"
    },
    {
      "effect": "The target suffers **(choose two: dazed, shaken, slow, weak)**.",
      "attr1": "insight",
      "attr2": "will",
      "special": [],
      "maxTargets": 1,
      "mp": "10",
      "target": "One creature",
      "name": "Curse XL",
      "duration": "Instantaneous",
      "damagetype": "physical",
      "type": "offensive",
      "itemType": "spell"
    },
    {
      "target": "One creature",
      "attr2": "will",
      "effect": "The target suffers **【HR + 15】 (choose type)** damage and suffers **(choose one: dazed,\nshaken, slow, weak).**",
      "name": "Cursed Breath",
      "damagetype": "physical",
      "special": [],
      "attr1": "insight",
      "duration": "Instantaneous",
      "maxTargets": 1,
      "type": "offensive",
      "itemType": "spell",
      "mp": "10"
    },
    {
      "maxTargets": 0,
      "duration": "Instantaneous",
      "mp": "30",
      "name": "Devastation",
      "attr2": "will",
      "special": [],
      "type": "",
      "effect": "Choose any number of creatures you can see: each of them suffers 30 **(choose type)** damage. You may only cast this spell **once per turn**.\nThis spell should only be given to **champion** and **elite** creatures **level 30 or higher**, and said creatures can only cast this spell during their **last turn in the round**.",
      "itemType": "spell",
      "attr1": "insight",
      "target": "Special",
      "damagetype": "physical"
    },
    {
      "target": "Self",
      "type": "",
      "attr2": "will",
      "maxTargets": 1,
      "effect": "You recover 20 Hit Points. This amount increases to 30 Hit Points if you are **level 20 or higher**, to 40 Hit Points if you are **level 40 or higher**, or to 50 Hit Points if you are **level 60** or higher.",
      "duration": "Instantaneous",
      "attr1": "insight",
      "special": [],
      "mp": "5",
      "itemType": "spell",
      "name": "Lick Wounds",
      "damagetype": "physical"
    },
    {
      "duration": "Instantaneous",
      "itemType": "spell",
      "effect": "The target suffers **【HR + 15】 (choose type)** damage. Then, you recover an amount of Hit Points equal to half the Hit Point loss they suffered.",
      "type": "offensive",
      "maxTargets": 1,
      "attr2": "will",
      "attr1": "insight",
      "damagetype": "physical",
      "special": [],
      "mp": "10",
      "name": "Life Theft",
      "target": "One creature"
    },
    {
      "itemType": "spell",
      "duration": "Instantaneous",
      "damagetype": "physical",
      "name": "Mind Theft",
      "type": "offensive",
      "attr2": "will",
      "effect": "The target suffers **【HR + 15】 (choose type)** damage. Then, you recover an amount of Mind Points equal to half the Hit Point loss they suffered.",
      "attr1": "insight",
      "special": [],
      "target": "One creature",
      "maxTargets": 1,
      "mp": "10"
    },
    {
      "maxTargets": 3,
      "duration": "Instantaneous",
      "attr2": "will",
      "name": "Poison",
      "itemType": "spell",
      "effect": "Each target hit by this spell suffers **poisoned**.",
      "attr1": "insight",
      "damagetype": "physical",
      "type": "offensive",
      "special": [],
      "mp": "10",
      "target": "Up to three creatures"
    },
    {
      "target": "One creature",
      "type": "",
      "attr1": "insight",
      "maxTargets": 1,
      "name": "Quicken",
      "attr2": "will",
      "mp": "20",
      "duration": "Instantaneous",
      "special": [],
      "effect": "The target may immediately perform a **free attack** with a weapon they have equipped (or with a basic **attack**, if the target is an NPC).",
      "damagetype": "physical",
      "itemType": "spell"
    },
    {
      "effect": "Each target hit by this spell suffers **enraged**.",
      "damagetype": "physical",
      "mp": "10",
      "duration": "Instantaneous",
      "attr2": "will",
      "type": "offensive",
      "maxTargets": 3,
      "attr1": "insight",
      "target": "Up to three creatures",
      "special": [],
      "itemType": "spell",
      "name": "Rage"
    },
    {
      "itemType": "spell",
      "effect": "Until this spell ends, you gain Resistance to **physical** damage.",
      "damagetype": "physical",
      "special": [],
      "mp": "10",
      "attr2": "will",
      "maxTargets": 1,
      "attr1": "insight",
      "duration": "Scene",
      "type": "",
      "target": "Self",
      "name": "Shell"
    },
    {
      "itemType": "spell",
      "attr1": "insight",
      "effect": "Until this spell ends, each target gains a +1 bonus to Accuracy Checks.",
      "name": "War Cry",
      "special": [],
      "attr2": "will",
      "target": "Up to three creatures",
      "type": "",
      "maxTargets": 3,
      "duration": "Scene",
      "mp": "10",
      "damagetype": "physical"
    },
    {
      "type": "offensive",
      "mp": "10",
      "damagetype": "physical",
      "maxTargets": 1,
      "name": "Weaken",
      "target": "One creature",
      "attr2": "will",
      "special": [],
      "attr1": "insight",
      "effect": "Until this spell ends, the target suffers 5 extra damage from all sources that deal **(choose type)** damage.",
      "itemType": "spell",
      "duration": "Scene"
    }
  ]