const BossSkill = {
	NOOP_BOSS_SKILL: Modifier.NOOP_BOSS_SKILL,
	CORROSIVE_STATUS: Modifier.CORROSIVE_STATUS,
	CRUSHING_ADVANTAGE: Modifier.CRUSHING_ADVANTAGE,
	ELEMENTAL_CRISIS: Modifier.ELEMENTAL_CRISIS,
	PART_REGENERATION: Modifier.PART_REGENERATION,
	TEMPORARY_DEFENSES: Modifier.TEMPORARY_DEFENSES,
	ZOMBIFICATION: Modifier.ZOMBIFICATION
}